<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        // Helper function to get Category ID by slug
        $get = fn(string $slug) => Category::where('slug', $slug)->first()?->id;

        $electronics   = $get('electronics');
        $fashion       = $get('fashion');
        $homeGarden    = $get('home-garden');
        $sports        = $get('sports-outdoors');
        $books         = $get('books');
        $health        = $get('health-beauty');
        $toys          = $get('toys-kids');
        $groceries     = $get('groceries');

        $products = [
            // ── Electronics ──────────────────────────────────────────────
            ['category_id' => $electronics, 'name' => 'Samsung Galaxy A54', 'sku' => 'ELE-001', 'price' => 29999, 'sale_price' => 27999, 'stock' => 50, 'is_featured' => true, 'short_description' => '6.4" FHD+ 120Hz display, 5000mAh battery', 'description' => 'Samsung Galaxy A54 features a stunning 6.4-inch FHD+ Super AMOLED display with 120Hz refresh rate, 5000mAh long-lasting battery, 50MP triple camera, and IP67 water resistance.'],
            ['category_id' => $electronics, 'name' => 'Apple iPhone 15', 'sku' => 'ELE-002', 'price' => 89999, 'sale_price' => null, 'stock' => 30, 'is_featured' => true, 'short_description' => 'A16 Bionic chip, 48MP main camera', 'description' => 'Experience the Apple iPhone 15 with its powerful A16 Bionic chip, stunning 48MP camera system, Dynamic Island, USB-C port, and an all-day battery life in a sleek design.'],
            ['category_id' => $electronics, 'name' => 'Xiaomi Redmi Note 12', 'sku' => 'ELE-003', 'price' => 18999, 'sale_price' => 16999, 'stock' => 75, 'is_featured' => false, 'short_description' => '6.67" AMOLED, 50MP camera, 5000mAh', 'description' => 'Xiaomi Redmi Note 12 delivers a premium AMOLED display, 50MP triple camera setup, and a massive 5000mAh battery with 33W fast charging at an affordable price.'],
            ['category_id' => $electronics, 'name' => 'OnePlus Nord CE 3', 'sku' => 'ELE-004', 'price' => 24999, 'sale_price' => null, 'stock' => 40, 'is_featured' => false, 'short_description' => 'Snapdragon 782G, 100W SuperVOOC', 'description' => 'OnePlus Nord CE 3 is powered by Snapdragon 782G, features a 108MP camera, 5000mAh battery with blazing 100W SuperVOOC fast charging, and a smooth 120Hz AMOLED display.'],
            ['category_id' => $electronics, 'name' => 'Sony WH-1000XM5 Headphones', 'sku' => 'ELE-005', 'price' => 35999, 'sale_price' => 29999, 'stock' => 25, 'is_featured' => true, 'short_description' => 'Industry-leading noise cancellation', 'description' => 'Sony WH-1000XM5 wireless headphones deliver industry-leading noise cancellation with 8 microphones, 30-hour battery life, multipoint connection, and crystal-clear hands-free calling.'],
            ['category_id' => $electronics, 'name' => 'JBL Charge 5 Speaker', 'sku' => 'ELE-006', 'price' => 7999, 'sale_price' => 6499, 'stock' => 60, 'is_featured' => false, 'short_description' => 'Portable waterproof Bluetooth speaker', 'description' => 'JBL Charge 5 portable Bluetooth speaker features bold JBL Pro Sound, IP67 waterproof & dustproof rating, 20-hour playtime, and built-in power bank to charge your devices.'],
            ['category_id' => $electronics, 'name' => 'Samsung 43" Smart TV', 'sku' => 'ELE-007', 'price' => 42999, 'sale_price' => 38999, 'stock' => 15, 'is_featured' => true, 'short_description' => '4K UHD, Tizen OS, HDR', 'description' => 'Samsung 43-inch 4K UHD Smart TV with Crystal Display technology, HDR support, Tizen OS with built-in streaming apps, and Auto Game Mode for the ultimate home entertainment experience.'],
            ['category_id' => $electronics, 'name' => 'Dell Inspiron 15 Laptop', 'sku' => 'ELE-008', 'price' => 55000, 'sale_price' => 49999, 'stock' => 20, 'is_featured' => false, 'short_description' => 'Intel Core i5, 8GB RAM, 512GB SSD', 'description' => 'Dell Inspiron 15 laptop powered by 12th Gen Intel Core i5 processor, 8GB DDR4 RAM, 512GB PCIe SSD, 15.6" FHD display, and Windows 11 Home for seamless productivity.'],
            ['category_id' => $electronics, 'name' => 'Canon EOS M50 Mark II Camera', 'sku' => 'ELE-009', 'price' => 45000, 'sale_price' => 42000, 'stock' => 12, 'is_featured' => false, 'short_description' => '24.1MP mirrorless, 4K video', 'description' => 'Canon EOS M50 Mark II mirrorless camera features a 24.1MP APS-C CMOS sensor, 4K video recording, Dual Pixel CMOS AF, built-in Wi-Fi & Bluetooth, and a flip-out touchscreen LCD.'],
            ['category_id' => $electronics, 'name' => 'TP-Link Archer C60 Router', 'sku' => 'ELE-010', 'price' => 3500, 'sale_price' => null, 'stock' => 100, 'is_featured' => false, 'short_description' => 'AC1350 Dual Band WiFi router', 'description' => 'TP-Link Archer C60 AC1350 Dual Band Wi-Fi router delivers combined speeds up to 1350Mbps, 5 external antennas for wide coverage, Beamforming technology, and easy Tether app setup.'],

            // ── Fashion ──────────────────────────────────────────────────
            ['category_id' => $fashion, 'name' => 'Classic Cotton T-Shirt', 'sku' => 'FSH-001', 'price' => 599, 'sale_price' => 499, 'stock' => 200, 'is_featured' => false, 'short_description' => '100% premium cotton, multiple colors', 'description' => 'Comfortable everyday T-shirt made from 100% premium combed cotton. Soft, breathable, and durable with a relaxed fit perfect for all-day wear. Available in multiple colors and sizes.'],
            ['category_id' => $fashion, 'name' => 'Slim Fit Jeans', 'sku' => 'FSH-002', 'price' => 1499, 'sale_price' => 1199, 'stock' => 80, 'is_featured' => true, 'short_description' => 'Premium denim, slim fit design', 'description' => 'Stylish slim fit jeans crafted from high-quality stretch denim. Designed for a modern silhouette with comfortable elastane blend, five-pocket styling, and durable construction.'],
            ['category_id' => $fashion, 'name' => 'Formal Cotton Dress Shirt', 'sku' => 'FSH-003', 'price' => 999, 'sale_price' => 849, 'stock' => 120, 'is_featured' => false, 'short_description' => 'Office-ready, wrinkle-resistant cotton', 'description' => 'Premium formal dress shirt made from 100% Egyptian cotton with wrinkle-resistant finish. Features a tailored fit, spread collar, and pearl buttons. Ideal for office and formal occasions.'],
            ['category_id' => $fashion, 'name' => "Women's Floral Anarkali Kurta", 'sku' => 'FSH-004', 'price' => 1299, 'sale_price' => 999, 'stock' => 90, 'is_featured' => true, 'short_description' => 'Elegant floral print ethnic wear', 'description' => "Beautiful women's Anarkali kurta with vibrant floral print on soft rayon fabric. Features three-quarter sleeves, straight fit, and intricate embroidery at the neckline. Perfect for festive occasions."],
            ['category_id' => $fashion, 'name' => "Men's Sports Running Shoes", 'sku' => 'FSH-005', 'price' => 2999, 'sale_price' => 2499, 'stock' => 60, 'is_featured' => false, 'short_description' => 'Lightweight, cushioned sole for running', 'description' => "High-performance men's running shoes with breathable mesh upper, EVA cushioned midsole, and non-slip rubber outsole. Designed for long-distance running with superior arch support and flexibility."],
            ['category_id' => $fashion, 'name' => "Women's Leather Handbag", 'sku' => 'FSH-006', 'price' => 1899, 'sale_price' => null, 'stock' => 45, 'is_featured' => true, 'short_description' => 'Genuine PU leather, spacious tote', 'description' => "Elegant women's tote handbag crafted from premium quality PU leather. Features multiple interior pockets, a secure zipper closure, adjustable shoulder strap, and stylish metal hardware."],
            ['category_id' => $fashion, 'name' => "Men's Slim Chino Pants", 'sku' => 'FSH-007', 'price' => 1299, 'sale_price' => 1099, 'stock' => 100, 'is_featured' => false, 'short_description' => 'Stretch chino, versatile daily wear', 'description' => "Versatile slim-fit chino pants made from premium stretch cotton blend. Features a flat front, mid-rise waist, and tapered leg design. Perfect for both casual and semi-formal occasions."],
            ['category_id' => $fashion, 'name' => 'Silk Embroidered Saree', 'sku' => 'FSH-008', 'price' => 3999, 'sale_price' => 3299, 'stock' => 30, 'is_featured' => true, 'short_description' => 'Handcrafted silk with zari embroidery', 'description' => 'Exquisite silk saree with intricate zari embroidery along the border and pallu. Comes with matching blouse piece. Perfect for weddings, festivals, and special celebrations.'],
            ['category_id' => $fashion, 'name' => "Men's Polo Shirt", 'sku' => 'FSH-009', 'price' => 799, 'sale_price' => 649, 'stock' => 150, 'is_featured' => false, 'short_description' => 'Pique cotton polo, classic fit', 'description' => "Classic men's polo shirt crafted from 100% pique cotton. Features a two-button placket, ribbed collar and cuffs, and side vents for a comfortable fit. Available in solid and striped designs."],
            ['category_id' => $fashion, 'name' => 'Genuine Leather Bifold Wallet', 'sku' => 'FSH-010', 'price' => 899, 'sale_price' => 699, 'stock' => 200, 'is_featured' => false, 'short_description' => 'Full-grain leather, RFID blocking', 'description' => 'Premium full-grain leather bifold wallet with RFID blocking technology. Features 6 card slots, 2 bill compartments, and an ID window. Slim profile that fits comfortably in any pocket.'],

            // ── Home & Garden ────────────────────────────────────────────
            ['category_id' => $homeGarden, 'name' => 'Non-Stick Frying Pan Set', 'sku' => 'HMG-001', 'price' => 1499, 'sale_price' => 1199, 'stock' => 55, 'is_featured' => true, 'short_description' => '3-piece granite-coated cookware', 'description' => 'Premium 3-piece non-stick frying pan set with granite coating for healthy cooking with minimal oil. Heat-resistant handles, compatible with all stovetops including induction, and dishwasher safe.'],
            ['category_id' => $homeGarden, 'name' => 'LED Desk Lamp with USB Charging', 'sku' => 'HMG-002', 'price' => 799, 'sale_price' => 649, 'stock' => 80, 'is_featured' => false, 'short_description' => '5 lighting modes, USB port, touch control', 'description' => 'Modern LED desk lamp with 5 color modes and 5 brightness levels. Features a built-in USB charging port, touch-sensitive controls, memory function, and flexible gooseneck arm for precise lighting.'],
            ['category_id' => $homeGarden, 'name' => 'Egyptian Cotton Bed Sheet Set', 'sku' => 'HMG-003', 'price' => 1699, 'sale_price' => 1399, 'stock' => 40, 'is_featured' => false, 'short_description' => '4-piece 400 thread count, king size', 'description' => 'Luxurious 4-piece bed sheet set made from 100% Egyptian cotton with 400 thread count. Includes flat sheet, fitted sheet, and 2 pillowcases. Soft, breathable, and gets softer with every wash.'],
            ['category_id' => $homeGarden, 'name' => 'Ceramic 20-Piece Dinner Set', 'sku' => 'HMG-004', 'price' => 2999, 'sale_price' => 2499, 'stock' => 25, 'is_featured' => true, 'short_description' => 'Service for 4, microwave & dishwasher safe', 'description' => 'Elegant 20-piece ceramic dinner set with classic white glaze and subtle embossed pattern. Includes dinner plates, side plates, soup bowls, and mugs. Microwave, dishwasher, and oven safe up to 200°C.'],
            ['category_id' => $homeGarden, 'name' => 'Retractable Garden Hose 30m', 'sku' => 'HMG-005', 'price' => 999, 'sale_price' => 799, 'stock' => 35, 'is_featured' => false, 'short_description' => 'Auto-retract, 8-pattern spray nozzle', 'description' => 'Self-retracting garden hose with 30-meter reach, tangle-free design, and 8-pattern spray nozzle. Features durable latex core, UV-resistant casing, and wall-mount bracket for easy storage.'],
            ['category_id' => $homeGarden, 'name' => 'Vacuum Insulated Water Bottle', 'sku' => 'HMG-006', 'price' => 599, 'sale_price' => 499, 'stock' => 100, 'is_featured' => false, 'short_description' => '1L stainless steel, 24hr cold / 12hr hot', 'description' => '1-liter double-wall vacuum insulated stainless steel water bottle. Keeps drinks cold for 24 hours and hot for 12 hours. BPA-free, leak-proof lid, and sweat-free exterior. Perfect for outdoor activities.'],
            ['category_id' => $homeGarden, 'name' => 'Bamboo Cutting Board Set of 3', 'sku' => 'HMG-007', 'price' => 699, 'sale_price' => 549, 'stock' => 70, 'is_featured' => false, 'short_description' => 'Eco-friendly bamboo, 3 sizes', 'description' => 'Set of 3 premium bamboo cutting boards in small, medium, and large sizes. Naturally antibacterial, knife-friendly surface, juice groove design, and easy-grip handles. Eco-friendly and sustainable.'],
            ['category_id' => $homeGarden, 'name' => '1.7L Rapid Boil Electric Kettle', 'sku' => 'HMG-008', 'price' => 1299, 'sale_price' => 999, 'stock' => 45, 'is_featured' => true, 'short_description' => '1500W, BPA-free, auto shut-off', 'description' => '1.7-liter electric kettle with 1500W rapid boiling element. Features automatic shut-off and boil-dry protection, 360° cordless base, BPA-free interior, and blue LED illumination while boiling.'],
            ['category_id' => $homeGarden, 'name' => 'Minimalist Wall Clock 30cm', 'sku' => 'HMG-009', 'price' => 899, 'sale_price' => null, 'stock' => 50, 'is_featured' => false, 'short_description' => 'Silent sweep movement, modern design', 'description' => 'Sleek 30cm minimalist wall clock with silent sweep quartz movement for a noise-free environment. Features a metal frame, clear glass cover, and large Arabic numerals. Requires 1 AA battery.'],
            ['category_id' => $homeGarden, 'name' => 'Velvet Throw Pillow Cover Set of 4', 'sku' => 'HMG-010', 'price' => 699, 'sale_price' => 549, 'stock' => 90, 'is_featured' => false, 'short_description' => '45x45cm, hidden zipper, 4 colors', 'description' => 'Set of 4 premium velvet throw pillow covers in coordinated colors. Features invisible zipper for easy removal, machine washable fabric, and a soft plush texture that adds warmth to any living space.'],

            // ── Sports & Outdoors ────────────────────────────────────────
            ['category_id' => $sports, 'name' => 'Anti-Slip Yoga Mat 6mm', 'sku' => 'SPT-001', 'price' => 999, 'sale_price' => 799, 'stock' => 80, 'is_featured' => false, 'short_description' => 'Eco-friendly TPE, 183x61cm, non-slip', 'description' => 'Premium 6mm thick yoga mat made from eco-friendly TPE material. Features a textured non-slip surface on both sides, alignment lines, and includes a carrying strap. Odor-free and easy to clean.'],
            ['category_id' => $sports, 'name' => 'Adjustable Dumbbell Set 20kg', 'sku' => 'SPT-002', 'price' => 3499, 'sale_price' => 2999, 'stock' => 30, 'is_featured' => true, 'short_description' => 'Chrome-plated, rubber grip, 2 bars', 'description' => 'Complete 20kg adjustable dumbbell set with chrome-plated weight plates, solid steel bars, and rubber-coated ends. Includes 2 dumbbell bars with spin-lock collars for quick weight adjustment.'],
            ['category_id' => $sports, 'name' => 'Nike Air Zoom Pegasus Running Shoes', 'sku' => 'SPT-003', 'price' => 6999, 'sale_price' => 5999, 'stock' => 40, 'is_featured' => true, 'short_description' => 'Responsive cushioning, breathable mesh', 'description' => 'Nike Air Zoom Pegasus running shoes feature Air Zoom unit in the forefoot for responsive cushioning, breathable mesh upper, foam midsole, and durable rubber outsole for smooth transitions on any terrain.'],
            ['category_id' => $sports, 'name' => 'Professional Badminton Racket Set', 'sku' => 'SPT-004', 'price' => 1499, 'sale_price' => 1199, 'stock' => 50, 'is_featured' => false, 'short_description' => '2 rackets, 3 shuttlecocks, carry bag', 'description' => 'Complete badminton set with 2 full carbon graphite rackets, 3 nylon shuttlecocks, and a protective carry bag. Suitable for intermediate to advanced players. Lightweight design for swift maneuverability.'],
            ['category_id' => $sports, 'name' => 'Adidas Football Size 5', 'sku' => 'SPT-005', 'price' => 999, 'sale_price' => 849, 'stock' => 60, 'is_featured' => false, 'short_description' => 'FIFA approved, thermally bonded', 'description' => 'Adidas official size 5 football with thermally bonded seams for superior roundness and water resistance. Features a textured surface for improved grip, consistent flight path, and high bounce retention.'],
            ['category_id' => $sports, 'name' => 'Adjustable Cycling Helmet', 'sku' => 'SPT-006', 'price' => 1299, 'sale_price' => null, 'stock' => 45, 'is_featured' => false, 'short_description' => 'CE certified, 21 vents, LED rear light', 'description' => 'CE-certified cycling helmet with 21 ventilation channels for superior airflow, dial fit system for easy size adjustment, integrated LED rear light, and removable sun visor. Suitable for adults.'],
            ['category_id' => $sports, 'name' => 'Resistance Bands Set of 5', 'sku' => 'SPT-007', 'price' => 699, 'sale_price' => 549, 'stock' => 100, 'is_featured' => false, 'short_description' => '10-50lbs progressive resistance levels', 'description' => 'Set of 5 resistance bands with progressive resistance levels from 10lbs to 50lbs. Made from 100% natural latex, includes door anchor, handles, ankle straps, and carrying bag. Perfect for home workouts.'],
            ['category_id' => $sports, 'name' => 'Padded Weightlifting Gym Gloves', 'sku' => 'SPT-008', 'price' => 549, 'sale_price' => 449, 'stock' => 75, 'is_featured' => false, 'short_description' => 'Wrist support, anti-slip, breathable', 'description' => 'Professional weightlifting gloves with padded palm, built-in wrist wrap support, and breathable microfiber back. Anti-slip grip for barbells and dumbbells. Machine washable with adjustable velcro closure.'],
            ['category_id' => $sports, 'name' => 'Speed Jump Rope with Ball Bearings', 'sku' => 'SPT-009', 'price' => 349, 'sale_price' => 279, 'stock' => 120, 'is_featured' => false, 'short_description' => 'Tangle-free steel cable, adjustable length', 'description' => 'High-speed jump rope with precision ball-bearing handles for smooth, tangle-free rotation. Features an adjustable PVC-coated steel cable, comfortable foam grip handles, and a portable carry bag.'],
            ['category_id' => $sports, 'name' => 'BPA-Free Sports Water Bottle 1L', 'sku' => 'SPT-010', 'price' => 499, 'sale_price' => null, 'stock' => 90, 'is_featured' => false, 'short_description' => 'Leak-proof flip lid, time markers', 'description' => '1-liter Tritan BPA-free sports water bottle with flip-top straw lid, motivational time markers, and easy-clean wide mouth. Leak-proof, drop-resistant, and compatible with standard bicycle bottle cages.'],

            // ── Books ────────────────────────────────────────────────────
            ['category_id' => $books, 'name' => 'Rich Dad Poor Dad', 'sku' => 'BOK-001', 'price' => 449, 'sale_price' => 399, 'stock' => 150, 'is_featured' => true, 'short_description' => 'Robert Kiyosaki – personal finance classic', 'description' => "Rich Dad Poor Dad by Robert T. Kiyosaki is the world's bestselling personal finance book. It teaches the fundamental difference between assets and liabilities, and how the rich build wealth through financial literacy."],
            ['category_id' => $books, 'name' => 'The Alchemist', 'sku' => 'BOK-002', 'price' => 349, 'sale_price' => 299, 'stock' => 120, 'is_featured' => false, 'short_description' => 'Paulo Coelho – inspirational fiction', 'description' => "The Alchemist by Paulo Coelho is a magical story about following your dreams. It follows a young Andalusian shepherd's journey to find worldly treasure and discovers a much greater treasure along the way."],
            ['category_id' => $books, 'name' => 'Atomic Habits', 'sku' => 'BOK-003', 'price' => 549, 'sale_price' => 499, 'stock' => 100, 'is_featured' => true, 'short_description' => 'James Clear – build good habits', 'description' => 'Atomic Habits by James Clear provides a proven framework for improving every day. Learn how tiny changes in behavior can lead to remarkable results and how to build good habits while breaking bad ones.'],
            ['category_id' => $books, 'name' => 'Think and Grow Rich', 'sku' => 'BOK-004', 'price' => 399, 'sale_price' => null, 'stock' => 80, 'is_featured' => false, 'short_description' => 'Napoleon Hill – classic success principles', 'description' => 'Think and Grow Rich by Napoleon Hill is one of the best-selling self-help books of all time. Based on interviews with 500+ millionaires, it outlines 13 principles for achieving success and financial independence.'],
            ['category_id' => $books, 'name' => 'The Psychology of Money', 'sku' => 'BOK-005', 'price' => 499, 'sale_price' => 449, 'stock' => 90, 'is_featured' => true, 'short_description' => 'Morgan Housel – timeless money lessons', 'description' => 'The Psychology of Money by Morgan Housel explores the strange ways people think about money and teaches you how to make better sense of one of life\'s most important subjects through 19 short stories.'],
            ['category_id' => $books, 'name' => 'Deep Work', 'sku' => 'BOK-006', 'price' => 449, 'sale_price' => 399, 'stock' => 70, 'is_featured' => false, 'short_description' => 'Cal Newport – rules for focused success', 'description' => 'Deep Work by Cal Newport argues that the ability to focus without distraction on cognitively demanding tasks is a superpower in our economy. Learn rules and strategies to cultivate a deep work habit.'],
            ['category_id' => $books, 'name' => '1984 by George Orwell', 'sku' => 'BOK-007', 'price' => 349, 'sale_price' => 299, 'stock' => 100, 'is_featured' => false, 'short_description' => 'Dystopian classic, totalitarian society', 'description' => "George Orwell's 1984 is a chilling dystopian masterpiece set in a totalitarian superstate where Big Brother watches every citizen. A timeless classic exploring truth, propaganda, and the nature of power."],
            ['category_id' => $books, 'name' => 'Harry Potter Complete Box Set (7 Books)', 'sku' => 'BOK-008', 'price' => 2999, 'sale_price' => 2499, 'stock' => 30, 'is_featured' => true, 'short_description' => 'J.K. Rowling – full series box set', 'description' => "The complete Harry Potter series by J.K. Rowling in a beautiful box set. All 7 books from The Philosopher's Stone to The Deathly Hallows. A perfect gift for readers of all ages."],
            ['category_id' => $books, 'name' => 'Clean Code', 'sku' => 'BOK-009', 'price' => 899, 'sale_price' => 799, 'stock' => 50, 'is_featured' => false, 'short_description' => 'Robert C. Martin – software craftsmanship', 'description' => "Clean Code by Robert C. Martin is a must-read for every software developer. It covers best practices for writing readable, maintainable code through real-world case studies and practical refactoring examples."],
            ['category_id' => $books, 'name' => 'The Pragmatic Programmer', 'sku' => 'BOK-010', 'price' => 999, 'sale_price' => 849, 'stock' => 45, 'is_featured' => false, 'short_description' => 'Hunt & Thomas – developer career guide', 'description' => 'The Pragmatic Programmer by Andrew Hunt and David Thomas is your journey to software mastery. Packed with practical advice, coding tips, and career guidance that remains relevant across all programming languages.'],

            // ── Health & Beauty ──────────────────────────────────────────
            ['category_id' => $health, 'name' => 'Vitamin C Brightening Serum', 'sku' => 'HLT-001', 'price' => 899, 'sale_price' => 749, 'stock' => 80, 'is_featured' => true, 'short_description' => '20% Vitamin C, hyaluronic acid, SPF-free', 'description' => 'Advanced Vitamin C face serum with 20% L-Ascorbic Acid, Vitamin E, and Hyaluronic Acid. Brightens dark spots, reduces fine lines, evens skin tone, and provides antioxidant protection. Suitable for all skin types.'],
            ['category_id' => $health, 'name' => 'SPF 50+ Sunscreen Cream 100ml', 'sku' => 'HLT-002', 'price' => 599, 'sale_price' => 499, 'stock' => 100, 'is_featured' => false, 'short_description' => 'Broad spectrum PA++++, non-greasy formula', 'description' => 'Broad-spectrum SPF 50+ PA++++ sunscreen with a lightweight, non-greasy formula. Provides UVA & UVB protection, contains niacinamide for brightening, and leaves no white cast. Suitable for daily use on all skin tones.'],
            ['category_id' => $health, 'name' => 'Biotin & Collagen Hair Supplement', 'sku' => 'HLT-003', 'price' => 1099, 'sale_price' => 899, 'stock' => 60, 'is_featured' => false, 'short_description' => '10,000mcg Biotin, 60 gummies per bottle', 'description' => 'Premium hair growth supplement with 10,000mcg Biotin, hydrolyzed collagen, Vitamin E, and zinc. Supports healthy hair growth, reduces hair fall, strengthens nails, and promotes glowing skin. 60 gummies per bottle.'],
            ['category_id' => $health, 'name' => 'Deep Moisturizing Face Cream 50ml', 'sku' => 'HLT-004', 'price' => 799, 'sale_price' => 649, 'stock' => 75, 'is_featured' => false, 'short_description' => 'Shea butter, ceramides, 48hr hydration', 'description' => 'Intensive moisturizing face cream enriched with Shea Butter, Ceramides, and Hyaluronic Acid. Provides 48-hour hydration, restores skin barrier, and reduces dryness and flakiness. Fragrance-free and dermatologist tested.'],
            ['category_id' => $health, 'name' => 'Electric Facial Gua Sha Massager', 'sku' => 'HLT-005', 'price' => 1699, 'sale_price' => 1399, 'stock' => 35, 'is_featured' => true, 'short_description' => 'EMS + vibration, 4 modes, USB-C charge', 'description' => 'Professional electric facial massager combining EMS microcurrent technology with vibration therapy. Features 4 modes for lifting, tightening, and de-puffing. Rechargeable via USB-C with 2-hour battery life.'],
            ['category_id' => $health, 'name' => 'Pure Organic Aloe Vera Gel 300ml', 'sku' => 'HLT-006', 'price' => 399, 'sale_price' => 329, 'stock' => 120, 'is_featured' => false, 'short_description' => '99% aloe vera, soothing & cooling', 'description' => '99% pure organic Aloe Vera gel with no added alcohol, parabens, or artificial colors. Soothes sunburn, reduces inflammation, moisturizes skin, tames frizzy hair, and can be used as a primer under makeup.'],
            ['category_id' => $health, 'name' => 'Professional Teeth Whitening Kit', 'sku' => 'HLT-007', 'price' => 999, 'sale_price' => 799, 'stock' => 50, 'is_featured' => false, 'short_description' => 'LED accelerator, 6 whitening gels, 14-day kit', 'description' => 'Complete professional teeth whitening kit with LED accelerator light, 6 whitening gel syringes, and custom mouth trays. Removes stains from coffee, tea, and tobacco. Results visible from day 1, full results in 14 days.'],
            ['category_id' => $health, 'name' => 'Gentle Foaming Facial Cleanser 150ml', 'sku' => 'HLT-008', 'price' => 549, 'sale_price' => 449, 'stock' => 90, 'is_featured' => false, 'short_description' => 'pH-balanced, removes makeup, no sulfates', 'description' => 'Gentle pH-balanced foaming face wash that effectively removes makeup, excess oil, and impurities without stripping the skin. Contains Niacinamide and Green Tea Extract. Sulfate-free, fragrance-free, non-comedogenic.'],
            ['category_id' => $health, 'name' => 'Bulgarian Rose Water Facial Toner 200ml', 'sku' => 'HLT-009', 'price' => 449, 'sale_price' => 349, 'stock' => 85, 'is_featured' => false, 'short_description' => '100% natural, hydrating, pore-minimizing', 'description' => '100% pure Bulgarian rose water toner that hydrates, tones, and refreshes the skin. Minimizes pores, reduces redness, sets makeup, and can be used as a hair mist. No alcohol, no parabens, no artificial fragrance.'],
            ['category_id' => $health, 'name' => 'Anti-Aging Eye Cream 30ml', 'sku' => 'HLT-010', 'price' => 1299, 'sale_price' => 1099, 'stock' => 40, 'is_featured' => true, 'short_description' => 'Retinol + peptides, reduces dark circles', 'description' => 'Advanced anti-aging eye cream with Retinol, Peptides, and Vitamin K. Reduces dark circles, puffiness, and crow\'s feet. Firms and brightens the delicate under-eye area. Ophthalmologist tested, safe for sensitive eyes.'],

            // ── Toys & Kids ──────────────────────────────────────────────
            ['category_id' => $toys, 'name' => 'LEGO Classic Creative Brick Box 484pcs', 'sku' => 'TOY-001', 'price' => 2199, 'sale_price' => 1799, 'stock' => 35, 'is_featured' => true, 'short_description' => '484 pieces, ages 4+, open-ended building', 'description' => 'LEGO Classic Creative Brick Box with 484 colorful pieces for endless open-ended building fun. Includes creative ideas booklet and features windows, doors, and wheels. Suitable for children ages 4 and above.'],
            ['category_id' => $toys, 'name' => 'Remote Control Monster Truck 1:16', 'sku' => 'TOY-002', 'price' => 1699, 'sale_price' => 1399, 'stock' => 40, 'is_featured' => false, 'short_description' => '4WD, 2.4GHz, high-speed off-road RC car', 'description' => '1:16 scale remote control monster truck with 4WD system, 2.4GHz interference-free control, and shock-absorbing suspension. Speeds up to 20km/h on various terrains. Includes rechargeable battery and USB charger.'],
            ['category_id' => $toys, 'name' => 'Baby Sensory Development Toy Set', 'sku' => 'TOY-003', 'price' => 599, 'sale_price' => 499, 'stock' => 70, 'is_featured' => false, 'short_description' => 'Rattle, teether, crinkle toys, 0-12 months', 'description' => 'Soft baby sensory toy set designed for newborns to 12-month-olds. Includes rattle, teething ring, crinkle toy, and activity mirror. Made from BPA-free, non-toxic materials. Stimulates sight, touch, and sound.'],
            ['category_id' => $toys, 'name' => "Children's Complete Art & Craft Set", 'sku' => 'TOY-004', 'price' => 849, 'sale_price' => 699, 'stock' => 55, 'is_featured' => false, 'short_description' => '143 pieces, ages 6+, washable colors', 'description' => "Complete 143-piece art and craft set for kids ages 6+. Includes watercolor paints, oil pastels, color pencils, crayons, sketch book, and brushes. Washable, non-toxic colors safe for children. Perfect for school projects."],
            ['category_id' => $toys, 'name' => 'Jigsaw Puzzle 500 Pieces Landscape', 'sku' => 'TOY-005', 'price' => 699, 'sale_price' => 549, 'stock' => 60, 'is_featured' => false, 'short_description' => 'HD printed, ages 10+, 50x70cm completed', 'description' => '500-piece jigsaw puzzle featuring a vibrant landscape scene. High-definition print on premium cardboard with linen finish. Completed size: 50x70cm. Suitable for ages 10 and above. Includes storage bag.'],
            ['category_id' => $toys, 'name' => 'Giant Plush Teddy Bear 60cm', 'sku' => 'TOY-006', 'price' => 999, 'sale_price' => 799, 'stock' => 45, 'is_featured' => true, 'short_description' => 'Super soft, machine washable, safe filling', 'description' => 'Giant 60cm teddy bear made from ultra-soft PP cotton plush fabric. Features hypoallergenic PP cotton filling, embroidered eyes for child safety, and machine washable design. Perfect birthday or gift for all ages.'],
            ['category_id' => $toys, 'name' => 'Pretend Play Kitchen Toy Set', 'sku' => 'TOY-007', 'price' => 2499, 'sale_price' => 1999, 'stock' => 20, 'is_featured' => true, 'short_description' => '27-piece accessories, lights & sounds, ages 3+', 'description' => 'Interactive pretend play kitchen set with realistic lights, sounds, and working knobs. Includes 27 food and cooking accessories, built-in refrigerator, oven, and microwave sections. Encourages imaginative play for ages 3+.'],
            ['category_id' => $toys, 'name' => 'Monopoly Classic Board Game', 'sku' => 'TOY-008', 'price' => 1099, 'sale_price' => 899, 'stock' => 40, 'is_featured' => false, 'short_description' => 'Classic version, 2-6 players, ages 8+', 'description' => 'The classic Monopoly board game for 2-6 players ages 8 and above. Includes game board, 8 tokens, property cards, Chance and Community Chest cards, houses, hotels, dice, and full-color money. 2-4 hours of fun.'],
            ['category_id' => $toys, 'name' => 'Watercolor & Sketch Drawing Set 120pc', 'sku' => 'TOY-009', 'price' => 649, 'sale_price' => null, 'stock' => 65, 'is_featured' => false, 'short_description' => '24 watercolors, 36 colors pencils, brushes', 'description' => '120-piece professional watercolor and sketching set including 24 watercolor pans, 36 colored pencils, 24 oil pastels, 12 sketch pencils, watercolor brushes, and a sketchpad. Ideal for beginners and students.'],
            ['category_id' => $toys, 'name' => 'Kids Balance Bicycle 16" No Pedal', 'sku' => 'TOY-010', 'price' => 4999, 'sale_price' => 4299, 'stock' => 15, 'is_featured' => true, 'short_description' => 'Lightweight aluminum, ages 3-6, adjustable seat', 'description' => 'Lightweight aluminum balance bike with 16-inch air tires, no pedals to help children aged 3-6 learn natural balancing skills. Features adjustable seat and handlebar height, soft EVA foam grips, and hand brake.'],

            // ── Groceries ────────────────────────────────────────────────
            ['category_id' => $groceries, 'name' => 'Premium Aged Basmati Rice 5kg', 'sku' => 'GRC-001', 'price' => 799, 'sale_price' => 699, 'stock' => 100, 'is_featured' => false, 'short_description' => '2-year aged, long grain, aromatic', 'description' => 'Premium 2-year aged Basmati rice with extra-long grains, aromatic fragrance, and fluffy non-sticky texture after cooking. Sourced from the foothills of the Himalayas. Ideal for biryani, pulao, and everyday meals.'],
            ['category_id' => $groceries, 'name' => 'Extra Virgin Olive Oil 500ml', 'sku' => 'GRC-002', 'price' => 999, 'sale_price' => 849, 'stock' => 70, 'is_featured' => true, 'short_description' => 'Cold-pressed, unfiltered, acidity < 0.2%', 'description' => 'Premium cold-pressed extra virgin olive oil from first-harvest olives with less than 0.2% acidity. Rich in polyphenols and Omega-3 fatty acids. Perfect for salad dressings, dipping, and low-heat cooking.'],
            ['category_id' => $groceries, 'name' => 'Raw Unfiltered Organic Honey 500g', 'sku' => 'GRC-003', 'price' => 699, 'sale_price' => 599, 'stock' => 80, 'is_featured' => false, 'short_description' => 'Wildflower, unpasteurized, no additives', 'description' => 'Pure raw wildflower honey harvested from organic beehives. Unprocessed, unpasteurized, and free from additives or preservatives. Naturally rich in enzymes, antioxidants, and beneficial pollen.'],
            ['category_id' => $groceries, 'name' => 'Premium Mixed Nuts & Dried Fruits 500g', 'sku' => 'GRC-004', 'price' => 899, 'sale_price' => 749, 'stock' => 65, 'is_featured' => true, 'short_description' => 'Cashews, almonds, walnuts, raisins, cranberries', 'description' => 'Premium assorted mix of dry-roasted cashews, blanched almonds, walnuts, raisins, and dried cranberries. No added salt, sugar, or preservatives. Lightly roasted for enhanced flavor. Resealable zip-lock pack.'],
            ['category_id' => $groceries, 'name' => 'Organic Green Tea 50 Bags', 'sku' => 'GRC-005', 'price' => 399, 'sale_price' => 329, 'stock' => 120, 'is_featured' => false, 'short_description' => 'Single-origin Darjeeling, EGCG rich', 'description' => 'Premium single-origin Darjeeling organic green tea with 50 unbleached pyramid bags. Rich in EGCG antioxidants, low caffeine, and naturally sweet flavor. USDA Organic and Rainforest Alliance certified.'],
            ['category_id' => $groceries, 'name' => 'Dark Chocolate 70% Cocoa 6-Pack', 'sku' => 'GRC-006', 'price' => 499, 'sale_price' => 419, 'stock' => 90, 'is_featured' => false, 'short_description' => 'Belgian cocoa, no palm oil, 6x50g bars', 'description' => 'Pack of 6 rich dark chocolate bars with 70% Belgian cocoa. Made with no palm oil, no artificial flavors, and minimal sugar. Each 50g bar delivers intense chocolate flavor with notes of coffee and fruit.'],
            ['category_id' => $groceries, 'name' => 'Rolled Oats 1kg Gluten-Free', 'sku' => 'GRC-007', 'price' => 349, 'sale_price' => 299, 'stock' => 100, 'is_featured' => false, 'short_description' => 'Certified gluten-free, high fiber, whole grain', 'description' => 'Certified gluten-free whole grain rolled oats with high fiber and slow-release energy. No added sugar, salt, or preservatives. Ideal for oatmeal, granola, smoothies, and baking. Resealable stand-up pouch.'],
            ['category_id' => $groceries, 'name' => 'Apple Cider Vinegar with Mother 500ml', 'sku' => 'GRC-008', 'price' => 449, 'sale_price' => 379, 'stock' => 75, 'is_featured' => false, 'short_description' => 'Raw, unfiltered, 5% acidity, USDA Organic', 'description' => 'Raw unfiltered organic apple cider vinegar with the "mother" of enzymes, proteins, and beneficial bacteria. 5% natural acidity. Supports digestion, immunity, and healthy blood sugar. Use in salads, tonics, and cooking.'],
            ['category_id' => $groceries, 'name' => 'Whey Protein Powder Chocolate 1kg', 'sku' => 'GRC-009', 'price' => 2299, 'sale_price' => 1999, 'stock' => 40, 'is_featured' => true, 'short_description' => '24g protein per serving, 33 servings', 'description' => 'Premium whey protein concentrate powder with 24g of protein per 30g serving (33 servings). Rich chocolate flavor, low sugar, fast-absorbing, and mixes easily. Ideal for post-workout muscle recovery and growth.'],
            ['category_id' => $groceries, 'name' => 'Organic Unsweetened Almond Milk 1L', 'sku' => 'GRC-010', 'price' => 399, 'sale_price' => 329, 'stock' => 85, 'is_featured' => false, 'short_description' => 'Dairy-free, vegan, calcium fortified', 'description' => 'Organic unsweetened almond milk made from whole almonds with no added sugar, artificial flavors, or preservatives. Fortified with Calcium and Vitamin D. Dairy-free, vegan, and lactose-free alternative for everyday use.'],
        ];

        foreach ($products as $data) {
            $slug = Str::slug($data['name']);
            Product::updateOrCreate(
                ['sku' => $data['sku']],
                array_merge($data, [
                    'slug'                => $slug,
                    'is_active'           => true,
                    'low_stock_threshold' => 5,
                    'average_rating'      => round(rand(35, 50) / 10, 1),
                    'reviews_count'       => rand(5, 120),
                ])
            );
        }
    }
}